### ISSUE TITLE
format catalog

### ISSUE THREAD

**Issue by davidwhogg** [aceilers/spectroscopic_parallax#20]
We need to strip down @aceilers data file to a sensible subset, make a fits file, format a table snippet in the paper, and figure out how to release the full file on arXiv with the paper.

**Comment by davidwhogg** [comment]
Of enormous relevance: https://arxiv.org/help/ancillary_files

**Comment by aceilers** [comment]
essential columns: 2MASS ID, spec parallax + error, sample name, training sample

**Comment by aceilers** [comment]
optional columns: Gaia parallax + error, Gaia + 2MASS + WISE photometry

**Comment by aceilers** [comment]
remind user that Gaia and spec parallax are independent!
