### ISSUE TITLE
WISE data

### ISSUE THREAD

**Issue by andyljones** [aceilers/spectroscopic_parallax#26]
Hey - I'm trying to get this code to run, but I can't find a way to download _just_ the part of the AllWISE catalogue that the GAIA crossmatch has given me IDs for. Do you know of a way? Or do I have to download the whole 300GB dataset and pluck out the rows I want? The IRSA APIs only seem to support geometric queries.

(It's not a huge problem if that is the only way - can chuck it all on S3 and SELECT through the bzips easily enough - but man, that's not very elegant)

**Comment by davidwhogg** [comment]
Can't you do the join to the allwise table in the Gaia Archive? What WISE columns do you want?

**Comment by andyljones** [comment]
Didn't realise the allwise table was there. Thanks!

**Comment by andyljones** [comment]
On a similar note - where can I find the 'pixlist' file mentioned [here](https://github.com/aceilers/spectroscopic_parallax/blob/master/normalize_all_spectra.py#L123)?

**Comment by davidwhogg** [comment]
@aceilers can you check in this file?

**Comment by aceilers** [comment]
Ok, it should be in the data folder now.
